#!/usr/bin/env groovy

def helpers


pipeline {
    options {
        ansiColor('xterm')
        buildDiscarder(logRotator(numToKeepStr: '10', artifactNumToKeepStr: '10'))
        disableConcurrentBuilds()
        skipDefaultCheckout(true)
        timeout(time: 1, unit: 'HOURS')
        timestamps()
    }

    agent {
        kubernetes {
            yamlFile '.ci/pod.yaml'
            defaultContainer 'base'
        }
    }

    stages {
        stage('Clone') {
            steps {
                script {
                    sh 'terraform --version'
                }
            }
        }
    }
}
