apiVersion: v1
kind: Pod
activeDeadlineSeconds: 1800
spec:
  imagePullSecrets:
    - registry-dub.tools.3stripes.net
  containers:
    - name: base
      image: registry-dub.tools.3stripes.net/da-lakehouse/infra-auto/base:4_569263465c
      # imagePullPolicy: Always
      tty: true
      command:
        - cat
      resources:
        requests:
          cpu: "2"
          memory: "2048Mi"
